# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('roadshop_name', models.CharField(choices=[('ETUDE_HOUSE', 'ETUDE_HOUSE'), ('THE_FACE_SHOP', 'THE_FACE_SHOP'), ('SKIN_FOOD', 'SKIN_FOOD'), ('MISSHA', 'MISSHA')], max_length=20)),
                ('start_date', models.DateTimeField(blank='', null=True)),
                ('end_date', models.DateTimeField(blank='', null=True)),
                ('describe', models.CharField(blank='', max_length=300, null=True)),
                ('image_url', models.CharField(blank='', max_length=300, null=True)),
                ('link_url', models.CharField(blank='', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
