# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadshops', '0003_auto_20151208_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadshops',
            name='roadshop_name',
            field=models.CharField(choices=[('ETUDE_HOUSE', 'ETUDE_HOUSE'), ('THE_FACE_SHOP', 'THE_FACE_SHOP'), ('SKIN_FOOD', 'SKIN_FOOD'), ('MISSHA', 'MISSHA'), ('ARITAUM', 'ARITAUM')], max_length=20),
        ),
    ]
