# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadshops', '0005_auto_20160105_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadshops',
            name='roadshop_name',
            field=models.CharField(choices=[('ETUDE_HOUSE', 'ETUDE_HOUSE'), ('THE_FACE_SHOP', 'THE_FACE_SHOP'), ('SKIN_FOOD', 'SKIN_FOOD'), ('MISSHA', 'MISSHA'), ('ARITAUM', 'ARITAUM'), ('INNISFREE', 'INNISFREE'), ('THE_SAEM', 'THE_SAEM')], max_length=20),
        ),
    ]
