# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadshops', '0006_auto_20160111_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadshops',
            name='roadshop_name',
            field=models.CharField(choices=[('ETUDE_HOUSE', 'ETUDE_HOUSE'), ('THE_FACE_SHOP', 'THE_FACE_SHOP'), ('SKIN_FOOD', 'SKIN_FOOD'), ('MISSHA', 'MISSHA'), ('ARITAUM', 'ARITAUM'), ('INNISFREE', 'INNISFREE'), ('THE_SAEM', 'THE_SAEM'), ('ITS_SKIN', 'ITS_SKIN'), ('NATURE_REPUBLIC', 'NATURE_REPUBLIC'), ('TONYMOLY', 'TONYMOLY')], max_length=20),
        ),
    ]
