# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadshops', '0007_auto_20160113_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadshops',
            name='is_active',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
