# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadshops', '0008_roadshops_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadshops',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 18, 4, 3, 17, 183518, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
